CREATE TABLE ESTADO (
	ID BIGINT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(80) NOT NULL,

    PRIMARY KEY (ID)
) ENGINE=InnoDB default charset=utf8;

INSERT INTO ESTADO (NOME) SELECT DISTINCT NOME_ESTADO FROM CIDADE;

ALTER TABLE CIDADE ADD COLUMN ESTADO_ID BIGINT NOT NULL; 

UPDATE CIDADE C SET C.ESTADO_ID = (SELECT E.ID FROM ESTADO E WHERE E.NOME = C.NOME_ESTADO);

ALTER TABLE CIDADE ADD CONSTRAINT FK_CIDADE_ESTADO FOREIGN KEY (ESTADO_ID)REFERENCES ESTADO (ID);

ALTER TABLE CIDADE DROP COLUMN NOME_ESTADO;

ALTER TABLE CIDADE CHANGE NOME_CIDADE NOME VARCHAR(80) NOT NULL;
